[package]
name = "dcr"
version = "0.1.0"
edition = "2021"

[dependencies]
rpassword = "7.3.1"
scraper = "0.21.0"
simple-base64 = "0.23.2"
ureq = { version = "2.10.1", default-features = false, features = ["gzip", "charset"] }
